#ifndef _TYPEDUCK_SETTINGS_RESOURCE_H_
#define _TYPEDUCK_SETTINGS_RESOURCE_H_

#define IDI_TYPEDUCK_SETTINGS 101
#define IDB_TYPEDUCK_ABOUT_BANNER 201
#define IDB_TYPEDUCK_CREDIT_LOGOS 202

#endif // _TYPEDUCK_SETTINGS_RESOURCE_H_
