name: Release CI

on:
  push:
    tags:
      - '**'

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yml

  release:
    needs: windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: "TypeDuck for Windows: ${{ github.ref_name }}"
          files: |
            artifact/*
